# frame specs
IMAGE_MAX_SIDE = 1280
VIDEO_MAX_SIDE = 1050

# canny thresholds
CANNY_LOWER_RATIO = 0.66
CANNY_UPPER_RATIO = 1.33
CANNY_FALLBACK_INC = 20

# gaussian blur sigma
GAUS_BASE_SIGMA = 1.5
GAUS_SIGMA_THRESH_HIGH = 500
GAUS_SIGMA_THRESH_MED = 200
GAUS_SIGMA_MULT_HIGH = 2.5
GAUS_SIGMA_MULT_MED = 1.5

# edge detection
MIN_BLUR_KERNEL = 3
SKETCH_BLUR = 3
SKETCH_THRESH_MULT = 1.8
CARTOON_EDGE_KERNEL_IMG = 3
CARTOON_EDGE_KERNEL_VID = 5
CARTOON_THRESH_MULT_VID = 1.5

# edge smoothing
EDGE_BUFFER_LEN = 2
EDGE_MIN_WEIGHT = 0.3
EDGE_MAX_WEIGHT = 0.8

# bilateral filter
BILATERAL_D = 7
BILATERAL_SIGMA_COLOR = 150
BILATERAL_SIGMA_SPACE = 75

# kmeans
KMEANS_SAMPLE_SIZE = 50000
KMEANS_RETRAIN_INTERVAL = 60
KMEANS_K_MIN = 20
KMEANS_K_MAX = 40
KMEANS_BATCH_IMG = 10000
KMEANS_BATCH_VID = 2000
KMEANS_BATCH_FIT = 3000

# cartoon
DARK_FACTOR = 0.4

# clahe
CLAHE_CLIP_LIMIT = 2.0
CLAHE_TILE_GRID = (8, 8)

# video processing
FFMPEG_VCODEC="libx264"
FFMPEG_CRF = 18
FFMPEG_PRESET = "ultrafast"
FFMPEG_PIX_FMT = "yuv420p"
FFMPEG_MAXRATE = "12M"
FFMPEG_BUFSIZE = "24M"
MAX_FPS = 24.0

# file exts
IMAGE_EXTENSIONS = [".jpg", ".jpeg", ".png", ".bmp", ".tiff"]
OUTPUT_IMAGE_EXT = ".png"
OUTPUT_VIDEO_EXT = ".mp4"